name: test-lsh
run-name: ${{ github.ref_name }}
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:

  test-lsh:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: sudo apt-get install -y libreadline-dev

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt

      - name: Run tests
        run: python tests/test_lsh.py

      - name: Publish Test Report
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: test-report
          path: reports
